services:
  api:
    container_name: hr-talent-admin-api
    build:
      dockerfile: Dockerfile.local
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - hr-talent-network
    depends_on:
      - database
  database:
    container_name: hr-talent-db
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ~/.docker-shared/postgresql:/var/lib/postgresql/data
    networks:
      - hr-talent-network
networks:
  hr-talent-network: