name: hr-talent-admin-api
on: push
jobs:
  deploy:
    name: 'Deploy hr-talent-admin-api'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/build'
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:latest
      PROFILE_ACTIVE: prod
      APP_NAME: ${{ secrets.GCP_APP_NAME }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
        run: 'cat .env >> $GITHUB_ENV'
      - name: 'Auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Authorize Docker push'
        run: 'gcloud auth configure-docker --quiet'
      - name: 'Build Docker image'
        run: 'docker build . -t $IMAGE_NAME'
      - name: 'Test Docker image'
        run: 'docker run -d -p 80:80 $IMAGE_NAME'
      - name: 'Push Docker image'
        run: 'docker push $IMAGE_NAME'
      - name: Deploy
        run: |-
          gcloud compute instances update-container ${{ secrets.GCP_APP_NAME }} \
            --zone ${{ secrets.INSTANCE_ZONE}} \
            --container-image $IMAGE_NAME
            --container-env POSTGRES_HOST=$POSTGRES_HOST
            --container-env POSTGRES_PORT=POSTGRES_PORT
            --container-env POSTGRES_USER=$POSTGRES_USER
            --container-env POSTGRES_DB=$POSTGRES_DB
            --container-env POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}