name: hr-talent-admin-api
on: push
jobs:
  deploy:
    name: 'Deploy hr-talent-admin-api'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    env:
      PROFILE_ACTIVE: prod
      GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
      APP_NAME: ${{ secrets.APP_NAME }}
      INSTANCE_ZONE: ${{ secrets.INSTANCE_ZONE}}
      REPOSITRORY: ${{ secrets.GCP_REGION }}-docker.pkg.dev
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      FRONTEND_URLS: ${{ secrets.FRONTEND_URLS }}
      JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
      JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }}
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_TIME }}
      TWO_FACTOR_AUTHENTICATION_APP_NAME: ${{ secrets.APP_NAME }}
      SSL_CERT_PATH: '/app/certs/cert.pem'
      SSL_KEY_PATH: '/app/certs/key.pem'
      PORT: '443'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
      - name: 'Docker auth configuration'
        run: gcloud auth configure-docker
      - name: Generate Image Tag
        run: |
          echo "IMAGE_URL=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.APP_NAME }}/${{ secrets.APP_NAME }}:${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: 'Build image'
        run: docker build --tag $IMAGE_URL .
      - name: 'Docker push image'
        run: |-
          gcloud auth configure-docker $REPOSITRORY
          docker push "$IMAGE_URL"
      - name: 'Deploy project'
        run: |-
          gcloud compute instances update-container $APP_NAME \
          --container-restart-policy=always \
          --zone $INSTANCE_ZONE \
          --container-image $IMAGE_URL \
          --container-env POSTGRES_HOST="$POSTGRES_HOST" \
          --container-env POSTGRES_PORT="$POSTGRES_PORT" \
          --container-env POSTGRES_USER="$POSTGRES_USER" \
          --container-env POSTGRES_DB="$POSTGRES_DB" \
          --container-env POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
          --container-env FRONTEND_URLS="$FRONTEND_URLS" \
          --container-env JWT_ACCESS_TOKEN_SECRET="$JWT_ACCESS_TOKEN_SECRET" \
          --container-env JWT_REFRESH_TOKEN_SECRET="$JWT_REFRESH_TOKEN_SECRET" \
          --container-env JWT_ACCESS_TOKEN_EXPIRATION_TIME="$JWT_ACCESS_TOKEN_EXPIRATION_TIME" \
          --container-env JWT_REFRESH_TOKEN_EXPIRATION_TIME="$JWT_REFRESH_TOKEN_EXPIRATION_TIME" \
          --container-env TWO_FACTOR_AUTHENTICATION_APP_NAME="$TWO_FACTOR_AUTHENTICATION_APP_NAME" \
          --container-env SSL_CERT_PATH="$SSL_CERT_PATH" \
          --container-env SSL_KEY_PATH="$SSL_KEY_PATH" \
          --container-env PORT="$PORT"